FROM python:3.9

# Set working directory
WORKDIR /src

# Copy directories into the container
COPY Datasets /src/Datasets

# Install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
# Run the application
CMD ["python","K Means Clustering - Exercise 2 ; Mobile Money on Financial Inclusion.py"]